################################################################################
# RuboCop setup
################################################################################
require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6


################################################################################
# Individual cop configurations
################################################################################

Layout/LineLength:
  Max: 120
