################################################################################
# RuboCop setup
################################################################################
require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6


################################################################################
# Individual cop configurations
################################################################################
Layout/LineLength:
  Max: 120

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 20

RSpec/NestedGroups:
  Max: 5

# These 3 rules require a trailing comma, if and only if every item is on its
# own line.
Style/TrailingCommaInArguments:    { EnforcedStyleForMultiline: comma }
Style/TrailingCommaInArrayLiteral: { EnforcedStyleForMultiline: comma }
Style/TrailingCommaInHashLiteral:  { EnforcedStyleForMultiline: comma }
