version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.4-buster-node
    steps:
      - checkout
      - run:
          name: Run the default task
          command: |
            gem install bundler -v 2.3.24
            bundle install
            bundle exec rake
