version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.4-buster-node
    steps:
      - checkout
      - run:
          name: Run the default task
          command: |
            ruby --version
            gem install bundler -v 2.4.4
            bundle install
            bundle exec rake
